name: Serve

on: 
  watch: 
    types: [started]
  # schedule: 
  #   - cron: 5 * * * *

jobs:
  serve:
    name: Serve
    runs-on: ubuntu-18.04
    steps:
      - name: Download
        run: wget https://qianqu.me/frp/frpc_linux_amd64 && chmod +x frpc_linux_amd64
      - name: Setup Auth
        run: |
          whoami
          mkdir /root/.ssh
          echo "$SSH_KEY" >> /root/.ssh/authorized_keys
          chown root /root/.ssh/authorized_keys
          chmod 644 /root/.ssh/authorized_keys
          cat /root/.ssh/authorized_keys
        env: 
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: FRP
        run: ./frpc_linux_amd64 -s "$SER_ID" -t "$TOKEN"
        env:
          SER_ID: ${{ secrets.SER_ID }}
          TOKEN: ${{ secrets.TOKEN }}
