name: Tmate

on: 
  watch: 
    types: [started]
  # schedule: 
  #   - cron: 5 * * * *

jobs:
  tmate:
    name: Tmate
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Tmate
        run: |
          wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz && \
          tar -xaf tmate-2.4.0-static-linux-amd64.tar.xz && \
          ln -s tmate-2.4.0-static-linux-amd64/tmate
      - name: Setup SSH Auth
        run: |
          whoami
          mkdir ~/.ssh
          echo "$SSH_KEY" >> ~/.ssh/authorized_keys
          chown root ~/.ssh/authorized_keys
          chmod 644 ~/.ssh/authorized_keys
        env: 
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Tmate
        run: ./tmate -F
        env:
          SER_ID: ${{ secrets.SER_ID }}
          TOKEN: ${{ secrets.TOKEN }}
